#ifndef _OUTPUTS
#define _OUTPUTS
#include "Control.h"
//*****************************************************************************************
#define OUT0_PORT			GPIOA
#define OUT0_MODER		GPIO_MODER_MODER1_0
#define OUT0_MODERALL	GPIO_MODER_MODER1
#define OUT0_PUPDR		GPIO_PUPDR_PUPDR1_0
#define OUT0_OTYPER		GPIO_OTYPER_OT1
#define OUT0_OFF			OUT0_PORT->ODR |= GPIO_ODR_ODR_1
#define OUT0_ON				OUT0_PORT->ODR &= ~GPIO_ODR_ODR_1

#define OUT1_PORT			GPIOA
#define OUT1_MODER		GPIO_MODER_MODER0_0
#define OUT1_MODERALL	GPIO_MODER_MODER0
#define OUT1_PUPDR		GPIO_PUPDR_PUPDR0_0
#define OUT1_OTYPER		GPIO_OTYPER_OT0
#define OUT1_OFF			OUT1_PORT->ODR |= GPIO_ODR_ODR_0
#define OUT1_ON				OUT1_PORT->ODR &= ~GPIO_ODR_ODR_0

#define OUT2_PORT			GPIOC
#define OUT2_MODER		GPIO_MODER_MODER13_0
#define OUT2_MODERALL	GPIO_MODER_MODER13
#define OUT2_PUPDR		GPIO_PUPDR_PUPDR13_0
#define OUT2_OTYPER		GPIO_OTYPER_OT13
#define OUT2_OFF			OUT2_PORT->ODR |= GPIO_ODR_ODR_13
#define OUT2_ON				OUT2_PORT->ODR &= ~GPIO_ODR_ODR_13

#define OUT3_PORT			GPIOB
#define OUT3_MODER		GPIO_MODER_MODER9_0
#define OUT3_MODERALL	GPIO_MODER_MODER9
#define OUT3_PUPDR		GPIO_PUPDR_PUPDR9_0
#define OUT3_OTYPER		GPIO_OTYPER_OT9
#define OUT3_OFF			OUT3_PORT->ODR |= GPIO_ODR_ODR_9
#define OUT3_ON				OUT3_PORT->ODR &= ~GPIO_ODR_ODR_9

#define OUT4_PORT			GPIOB
#define OUT4_MODER		GPIO_MODER_MODER8_0
#define OUT4_MODERALL	GPIO_MODER_MODER8
#define OUT4_PUPDR		GPIO_PUPDR_PUPDR8_0
#define OUT4_OTYPER		GPIO_OTYPER_OT8
#define OUT4_OFF			OUT4_PORT->ODR |= GPIO_ODR_ODR_8
#define OUT4_ON				OUT4_PORT->ODR &= ~GPIO_ODR_ODR_8

#define OUT5_PORT			GPIOB
#define OUT5_MODER		GPIO_MODER_MODER7_0
#define OUT5_MODERALL	GPIO_MODER_MODER7
#define OUT5_PUPDR		GPIO_PUPDR_PUPDR7_0
#define OUT5_OTYPER		GPIO_OTYPER_OT7
#define OUT5_OFF 			OUT5_PORT->ODR |= GPIO_ODR_ODR_7
#define OUT5_ON				OUT5_PORT->ODR &= ~GPIO_ODR_ODR_7

#define OUT6_PORT			GPIOB
#define OUT6_MODER		GPIO_MODER_MODER6_0
#define OUT6_MODERALL	GPIO_MODER_MODER6
#define OUT6_PUPDR		GPIO_PUPDR_PUPDR6_0
#define OUT6_OTYPER		GPIO_OTYPER_OT6
#define OUT6_OFF			OUT6_PORT->ODR |= GPIO_ODR_ODR_6
#define OUT6_ON				OUT6_PORT->ODR &= ~GPIO_ODR_ODR_6

#define OUT7_PORT			GPIOB
#define OUT7_MODER		GPIO_MODER_MODER5_0
#define OUT7_MODERALL	GPIO_MODER_MODER5
#define OUT7_PUPDR		GPIO_PUPDR_PUPDR5_0
#define OUT7_OTYPER		GPIO_OTYPER_OT5
#define OUT7_OFF			OUT7_PORT->ODR |= GPIO_ODR_ODR_5
#define OUT7_ON				OUT7_PORT->ODR &= ~GPIO_ODR_ODR_5


#define OUT8_PORT			GPIOC
#define OUT8_MODER		GPIO_MODER_MODER9_0
#define OUT8_MODERALL	GPIO_MODER_MODER9
#define OUT8_PUPDR		GPIO_PUPDR_PUPDR9_0
#define OUT8_OTYPER		GPIO_OTYPER_OT9
#define OUT8_OFF			OUT8_PORT->ODR |= GPIO_ODR_ODR_9
#define OUT8_ON				OUT8_PORT->ODR &= ~GPIO_ODR_ODR_9

#define OUT9_PORT			GPIOA
#define OUT9_MODER		GPIO_MODER_MODER15_0
#define OUT9_MODERALL	GPIO_MODER_MODER15
#define OUT9_PUPDR		GPIO_PUPDR_PUPDR15_0
#define OUT9_OTYPER		GPIO_OTYPER_OT15
#define OUT9_OFF			OUT9_PORT->ODR |= GPIO_ODR_ODR_15
#define OUT9_ON				OUT9_PORT->ODR &= ~GPIO_ODR_ODR_15

#define OUT10_PORT			GPIOC
#define OUT10_MODER			GPIO_MODER_MODER10_0
#define OUT10_MODERALL	GPIO_MODER_MODER10
#define OUT10_PUPDR			GPIO_PUPDR_PUPDR10_0
#define OUT10_OTYPER		GPIO_OTYPER_OT10
#define OUT10_OFF				OUT10_PORT->ODR |= GPIO_ODR_ODR_10
#define OUT10_ON				OUT10_PORT->ODR &= ~GPIO_ODR_ODR_10

#define OUT11_PORT			GPIOC
#define OUT11_MODER			GPIO_MODER_MODER11_0
#define OUT11_MODERALL	GPIO_MODER_MODER11
#define OUT11_PUPDR			GPIO_PUPDR_PUPDR11_0
#define OUT11_OTYPER		GPIO_OTYPER_OT11
#define OUT11_OFF				OUT11_PORT->ODR |= GPIO_ODR_ODR_11
#define OUT11_ON				OUT11_PORT->ODR &= ~GPIO_ODR_ODR_11

#define OUT12_PORT			GPIOC
#define OUT12_MODER			GPIO_MODER_MODER12_0
#define OUT12_MODERALL	GPIO_MODER_MODER12
#define OUT12_PUPDR			GPIO_PUPDR_PUPDR12_0
#define OUT12_OTYPER		GPIO_OTYPER_OT12
#define OUT12_OFF				OUT12_PORT->ODR |= GPIO_ODR_ODR_12
#define OUT12_ON				OUT12_PORT->ODR &= ~GPIO_ODR_ODR_12

#define OUT13_PORT			GPIOB
#define OUT13_MODER			GPIO_MODER_MODER11_0
#define OUT13_MODERALL	GPIO_MODER_MODER11
#define OUT13_PUPDR			GPIO_PUPDR_PUPDR11_0
#define OUT13_OTYPER		GPIO_OTYPER_OT11
#define OUT13_OFF				OUT13_PORT->ODR |= GPIO_ODR_ODR_11
#define OUT13_ON				OUT13_PORT->ODR &= ~GPIO_ODR_ODR_11

#define OUT14_PORT			GPIOB
#define OUT14_MODER			GPIO_MODER_MODER3_0
#define OUT14_MODERALL	GPIO_MODER_MODER3
#define OUT14_PUPDR			GPIO_PUPDR_PUPDR3_0
#define OUT14_OTYPER		GPIO_OTYPER_OT3
#define OUT14_OFF				OUT14_PORT->ODR |= GPIO_ODR_ODR_3
#define OUT14_ON				OUT14_PORT->ODR &= ~GPIO_ODR_ODR_3

#define OUT15_PORT			GPIOB
#define OUT15_MODER			GPIO_MODER_MODER4_0
#define OUT15_MODERALL	GPIO_MODER_MODER4
#define OUT15_PUPDR			GPIO_PUPDR_PUPDR4_0
#define OUT15_OTYPER		GPIO_OTYPER_OT4
#define OUT15_OFF				OUT15_PORT->ODR |= GPIO_ODR_ODR_4
#define OUT15_ON				OUT15_PORT->ODR &= ~GPIO_ODR_ODR_4


void Outputs_Conf(void);
void Outputs_WorkTypeStop(void);
void Outputs_WorkTypeRun(void);
void Outputs_WorkTypeConf(void);
void Outputs_WorkTypeError(void);


#endif
